apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-migration
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: liquibase
          image: liquibase/liquibase
          env:
            - name: RAW_SECRET
              valueFrom:
                secretKeyRef:
                  name: mckingapi-secrets
                  key: postgres-connection-string
          command: ["/bin/sh", "-c"]
          args:
            - |
              HOST=$(echo $RAW_SECRET | sed -n 's/.*Host=\([^;]*\);.*/\1/p');
              DB=$(echo $RAW_SECRET | sed -n 's/.*Database=\([^;]*\);.*/\1/p');
              USER=$(echo $RAW_SECRET | sed -n 's/.*Username=\([^;]*\);.*/\1/p');
              PASS=$(echo $RAW_SECRET | sed -n 's/.*Password=\([^;]*\).*/\1/p');
              URL="jdbc:postgresql://$HOST/$DB?user=$USER&password=$PASS";
              echo \"Using URL: $URL\";
              liquibase --url=$URL --changeLogFile=/liquibase/changelog/db.changelog-master.xml update;
          volumeMounts:
            - name: changelog-volume
              mountPath: /liquibase/changelog
      volumes:
        - name: changelog-volume
          configMap:
            name: liquibase-changelog-cm
      restartPolicy: Never
  backoffLimit: 1
