name: Liquibase Migration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  liquibase:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Get DB Credentials from AWS Secrets Manager
        id: get_secret
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id aws-secretsmanager-secret-teste-4 --query SecretString --output text)

          # Extrair partes do segredo
          HOST_PORT=$(echo $SECRET | sed -n 's/.*Host=\([^;]*\);.*/\1/p')
          DATABASE=$(echo $SECRET | sed -n 's/.*Database=\([^;]*\);.*/\1/p')
          USERNAME=$(echo $SECRET | sed -n 's/.*Username=\([^;]*\);.*/\1/p')
          PASSWORD=$(echo $SECRET | sed -n 's/.*Password=\([^;]*\).*/\1/p')

          JDBC_URL="jdbc:postgresql://$HOST_PORT/$DATABASE?user=$USERNAME&password=$PASSWORD"

          echo "DB_URL=$JDBC_URL" >> $GITHUB_ENV

      - name: Run Liquibase Migration
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/liquibase/changelog:/liquibase/changelog \
            liquibase/liquibase \
            --url="${{ env.DB_URL }}" \
            --changeLogFile=changelog/db.changelog-master.xml \
            update
